
---
- name: Deploy MikroTik RouterOS with Docker Compose
  hosts: all 
  become: true
  vars:
    mikrotik_src: /root/mikrotik
    compose_file: "{{ mikrotik_src }}/docker-compose.yml"

  tasks:
    - name: Install general prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3
          - python3-pip
        update_cache: yes
      when: ansible_facts.packages['docker-ce'] is not defined

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-compose-plugin
          - docker-buildx-plugin
        update_cache: yes
        state: latest

    - name: Install Docker module for Python
      ansible.builtin.pip:
        name: 
          - "docker==6.1.3"
        state: present

    - name: Ensure Docker service is started
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create mikrotik folder
      file:
        path: "{{ mikrotik_src }}"
        state: directory
        
    - name: Copy Docker Compose file
      template:
        src: ./templates/docker-compose.yml.j2
        dest: "{{ compose_file }}"

    - name: Pull latest images and bring up services
      community.docker.docker_compose_v2:
        project_src: "{{ compose_file | dirname }}"
        pull: missing
        recreate: auto

